#!/data/data/com.termux/files/usr/bin/bash

export LD_LIBRARY_PATH=$HOME/RANSOMWARE/.data/binaries/lib/arm:$LD_LIBRARY_PATH
umask 000
cd $HOME/RANSOMWARE/.data/binaries
exec java -Xmx1024m -Djava.io.tmpdir=$HOME/RANSOMWARE/ -jar $HOME/RANSOMWARE/.data/binaries/apktool-2.2.2.jar -p $HOME/RANSOMWARE/ "$@"

